### POST request to example server
POST http://localhost:4004/api/patients
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name":"kafka",
    "email":"athang123@gmail.com",
    "address":"thane",
    "dateOfBirth":"1997-05-19",
    "registeredDate":"2025-03-18"
}

###