# update patient entity
PUT http://localhost:4004/api/patients/223e4567-e89b-12d3-a456-426614174009
Content-Type: application/json

{
  "name":"Chinmay",
  "email":"cna_updated@gmail.com",
  "address":"thane",
  "dateOfBirth":"1993-12-30"
}


###